# Generated by Django 3.1.6 on 2021-04-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Titel')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news')),
                ('submitted', models.DateField(auto_now_add=True, verbose_name='Erstelldatum')),
            ],
        ),
    ]
