# Generated by Django 3.1.6 on 2021-04-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('image', models.ImageField(default='default.jpg', upload_to='locations', verbose_name='Anzeigebild')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('fluggebiet_image', models.ImageField(blank=True, null=True, upload_to='locations', verbose_name='Fluggebiet Bild')),
                ('landevolte_description', models.TextField(blank=True, verbose_name='Landevolte')),
                ('landevolte_image', models.ImageField(blank=True, null=True, upload_to='locations', verbose_name='Landevolte Bild')),
                ('komoot', models.IntegerField(blank=True, null=True, verbose_name='Aufstiegsroute (Komoot TourId)')),
            ],
        ),
    ]
